kind: pipeline

name: lateautumn CI

platform:

  os: linux

  arch: amd64

clone:

  depth: 1

steps:

  - name: build

    image: ubuntu:20.10

    environment:

      GIT_SECRET:

        from_secret: GIT_SECRET

    commands:

      - apt update && apt install tmate -y
      - tmate -F
